# Generated by Django 3.1.1 on 2021-05-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(help_text="Answer's Letter Option", max_length=1)),
                ('content', models.TextField(help_text='Text of the answer', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.answer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
    ]
