# Generated by Django 3.1.1 on 2022-08-17 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de cadastro da resposta')),
                ('alternativa_escolhida', models.CharField(max_length=1)),
                ('alternativa_correta', models.BooleanField(default=False, help_text='A alternativa escolhida está correta?')),
                ('questao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_respostas', to='question.questao')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['data_resposta'],
            },
        ),
    ]
