# Generated by Django 3.1.1 on 2022-02-26 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLogQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data resposta')),
                ('selected_answer', models.CharField(max_length=255, verbose_name='Alternativa escolhida')),
                ('is_correct', models.CharField(max_length=255, verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Custom Log',
                'verbose_name_plural': 'Custom Logs',
                'ordering': ['date'],
            },
        ),
    ]
