# Generated by Django 3.1.1 on 2022-03-15 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='text',
        ),
        migrations.AddField(
            model_name='answers',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='reply date'),
        ),
        migrations.AddField(
            model_name='answers',
            name='is_correct',
            field=models.BooleanField(default=True, verbose_name='is the answer correct'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_a',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_b',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_c',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_d',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_e',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
