# Generated by Django 3.1.1 on 2022-01-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='option', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='option', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(default='option', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='option', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option_e',
            field=models.CharField(default='option', max_length=100),
        ),
    ]
