# Generated by Django 3.1.1 on 2020-11-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question_id', 'letter')},
        ),
    ]
