# Generated by Django 3.1.1 on 2022-03-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20220315_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='user',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
