# Generated by Django 3.1.1 on 2021-05-10 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210507_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.answer'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question_ref_id', 'letter')},
        ),
    ]
