# Generated by Django 3.1.1 on 2021-12-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_questionrecords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionrecords',
            old_name='correct_answered',
            new_name='is_correct_answered',
        ),
        migrations.AlterField(
            model_name='questionrecords',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
