# Generated by Django 3.1.1 on 2022-08-18 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0002_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='usuario',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='minhas_respostas', to='auth.user'),
            preserve_default=False,
        ),
    ]
